In [2]:
import pandas as pd

In [8]:
df = pd.read_parquet("../data/AL_PE/solar/tp_pca.parquet")
df.head()

,time,split,tp_pca_0,tp_pca_1,tp_pca_2,tp_pca_3,tp_pca_4,tp_pca_5,tp_pca_6,tp_pca_7,...,tp_pca_17,tp_pca_18,tp_pca_19,tp_pca_20,tp_pca_21,tp_pca_22,tp_pca_23,tp_pca_24,tp_pca_25,tp_pca_26
0,2023-10-01 00:00:00,train,-3.404893,-0.815640,0.521174,0.378232,-0.091521,-0.111505,-0.136564,0.182910,...,0.018532,0.006157,-0.005378,0.012089,-0.020795,-0.019433,0.017973,-0.006630,-0.026677,0.031485
1,2023-10-01 01:00:00,train,-3.878442,-1.494835,1.009456,0.684086,-0.377834,-0.178046,0.098748,0.324592,...,0.029869,0.004399,0.017776,0.079433,-0.022733,-0.032560,-0.038701,0.009948,0.000158,-0.004674
2,2023-10-01 02:00:00,train,-3.863750,-1.472855,0.981889,0.682513,-0.335255,-0.193920,0.114212,0.291216,...,0.016284,0.019231,-0.012722,0.066651,-0.017539,0.012064,-0.013330,0.031698,-0.017078,0.020577
3,2023-10-01 03:00:00,train,-3.832740,-1.428602,0.916898,0.692635,-0.233412,-0.239813,0.182367,0.209114,...,-0.038828,0.056767,-0.082617,0.034541,-0.013696,0.127747,0.070342,0.101140,-0.076953,0.075469
4,2023-10-01 04:00:00,train,-3.785461,-1.358123,0.819095,0.698616,-0.096371,-0.297067,0.257096,0.122783,...,-0.052654,0.051515,-0.111673,0.050489,0.001018,0.149855,0.112086,0.122341,-0.104224,0.108646

In [10]:
df = pd.read_parquet("../data/date_features.parquet")
df.head()

,time,hour_sin,hour_cos,week_day_sin,week_day_cos,month_day_sin,month_day_cos,month_sin,month_cos
0,2023-10-01 00:00:00,0.000000,1.000000,-0.781831,0.62349,0.0,1.0,-0.866025,0.5
1,2023-10-01 01:00:00,0.258819,0.965926,-0.781831,0.62349,0.0,1.0,-0.866025,0.5
2,2023-10-01 02:00:00,0.500000,0.866025,-0.781831,0.62349,0.0,1.0,-0.866025,0.5
3,2023-10-01 03:00:00,0.707107,0.707107,-0.781831,0.62349,0.0,1.0,-0.866025,0.5
4,2023-10-01 04:00:00,0.866025,0.500000,-0.781831,0.62349,0.0,1.0,-0.866025,0.5