In [1]:
import pandas as pd
from datetime import datetime

In [2]:
coff_eol = pd.read_parquet("../data/processed/coff/constrained_off_eolica_detail.parquet")

In [3]:
ne_geoelet = coff_eol.loc[coff_eol['id_estado'].isin(["CE", "BA", "PE", "PI", "MA", "RN", "PB", "AL", "SE"])]
ne_geoelet.head()

,id_subsistema,id_estado,nom_modalidadeoperacao,nom_conjuntousina,nom_usina,id_ons,ceg,din_instante,val_ventoverificado,flg_dadoventoinvalido,val_geracaoestimada,val_geracaoverificada,fonte,ano,mes,data,hora,minuto,ano_mes,arquivo_origem
0,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas XV,BAB15,EOL.CV.BA.038031-8.01,2023-01-01,8.750,1.0,0.000,21.018,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
1,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas XX,BAB20,EOL.CV.BA.036993-4.01,2023-01-01,8.500,1.0,0.000,17.149,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
2,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas IV,BABAQ,EOL.CV.BA.038032-6.01,2023-01-01,7.937,1.0,0.000,36.640,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
3,NE,BA,Tipo II-C,Conj. Gentio do Ouro I,Assuruá II,BAEA02,EOL.CV.BA.031343-2.01,2023-01-01,13.757,0.0,30.062,25.602,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
4,NE,BA,Tipo II-C,Conj. Gentio do Ouro I,Assuruá III,BAEA03,EOL.CV.BA.032342-0.01,2023-01-01,14.411,0.0,12.856,11.970,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet

In [4]:
def fill_estimativa(row):
    estimada, verificada = row
    if estimada == 0:
        return verificada
    return estimada


ne_geoelet['val_geracaoestimada'] = ne_geoelet[['val_geracaoestimada', 'val_geracaoverificada']].apply(fill_estimativa, axis=1)

In [5]:
ne_geoelet.head()

,id_subsistema,id_estado,nom_modalidadeoperacao,nom_conjuntousina,nom_usina,id_ons,ceg,din_instante,val_ventoverificado,flg_dadoventoinvalido,val_geracaoestimada,val_geracaoverificada,fonte,ano,mes,data,hora,minuto,ano_mes,arquivo_origem
0,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas XV,BAB15,EOL.CV.BA.038031-8.01,2023-01-01,8.750,1.0,21.018,21.018,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
1,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas XX,BAB20,EOL.CV.BA.036993-4.01,2023-01-01,8.500,1.0,17.149,17.149,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
2,NE,BA,Tipo II-C,Conj. Arizona,Baraúnas IV,BABAQ,EOL.CV.BA.038032-6.01,2023-01-01,7.937,1.0,36.640,36.640,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
3,NE,BA,Tipo II-C,Conj. Gentio do Ouro I,Assuruá II,BAEA02,EOL.CV.BA.031343-2.01,2023-01-01,13.757,0.0,30.062,25.602,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet
4,NE,BA,Tipo II-C,Conj. Gentio do Ouro I,Assuruá III,BAEA03,EOL.CV.BA.032342-0.01,2023-01-01,14.411,0.0,12.856,11.970,eolica,2023,1,2023-01-01,0,0,2023-01,RESTRICAO_COFF_EOLICA_DETAIL_2023_01.parquet

In [6]:
grupo_ne = ne_geoelet.groupby(['din_instante', 'id_estado', 'fonte']).agg(
    {'val_geracaoestimada': 'sum',
     'val_geracaoverificada': 'sum'
     }).reset_index(drop=False)

In [ ]:
grupo_ne.loc[grupo_ne['id_estado'] == 'BA']

,din_instante,id_estado,fonte,val_geracaoestimada,val_geracaoverificada
0,2023-01-01 00:00:00,BA,eolica,4846.597,4759.630
1,2023-01-01 00:00:00,CE,eolica,1189.828,1208.167
2,2023-01-01 00:00:00,MA,eolica,226.139,209.612
3,2023-01-01 00:00:00,PB,eolica,369.091,378.626
4,2023-01-01 00:00:00,PE,eolica,648.573,661.611
...,...,...,...,...,...
449899,2026-08-31 23:30:00,MA,eolica,380.629,369.369
449900,2026-08-31 23:30:00,PB,eolica,672.657,573.614
449901,2026-08-31 23:30:00,PE,eolica,741.756,720.247
449902,2026-08-31 23:30:00,PI,eolica,2460.310,2267.063
449903,2026-08-31 23:30:00,RN,eolica,5701.486,4409.750